"""Automation generation and YAML synthesis engine for SwitchMatrix."""
from __future__ import annotations

import logging
import os
from typing import Any
import uuid
import yaml

from homeassistant.core import HomeAssistant
from homeassistant.helpers.storage import Store

from .const import (
    ACTION_DOUBLE_PRESS,
    ACTION_LONG_PRESS,
    ACTION_PRESS,
    ACTION_RELEASE,
    ACTION_ROTATE_CCW,
    ACTION_ROTATE_CW,
    ACTION_TRIPLE_PRESS,
    STORAGE_KEY,
    STORAGE_VERSION,
)

_LOGGER = logging.getLogger(__name__)


class AutomationBuilder:
    """Constructs, validates, and serializes Home Assistant automations."""

    def __init__(self, hass: HomeAssistant) -> None:
        self.hass = hass
        self.store = Store(hass, STORAGE_VERSION, STORAGE_KEY)

    def build_automation(self, flow_data: dict[str, Any]) -> dict[str, Any]:
        """Convert a SwitchMatrix UI flow graph into a standard Home Assistant automation dict."""
        auto_id = flow_data.get("id") or f"switchmatrix_{uuid.uuid4().hex[:8]}"
        alias = flow_data.get("alias") or f"SwitchMatrix: {flow_data.get('zone_label', 'Switch Action')}"
        description = flow_data.get("description") or "Generated by SwitchMatrix Visual Switch Automation Builder"

        # 1. Trigger Synthesis
        trigger = self._build_trigger(flow_data)

        # 2. Condition Synthesis
        conditions = self._build_conditions(flow_data.get("conditions", []))

        # 3. Action Synthesis
        actions = self._build_actions(flow_data.get("action", {}))

        automation_dict: dict[str, Any] = {
            "id": auto_id,
            "alias": alias,
            "description": description,
            "mode": flow_data.get("mode", "restart"),
            "trigger": trigger,
            "action": actions,
        }

        if conditions:
            automation_dict["condition"] = conditions

        return automation_dict

    def _build_trigger(self, flow: dict[str, Any]) -> list[dict[str, Any]]:
        """Construct universal trigger based on protocol and entity/device info."""
        entity_id = flow.get("entity_id")
        action_type = flow.get("action_type", ACTION_PRESS)
        device_id = flow.get("device_id")
        protocol = flow.get("protocol", "generic")

        # Case A: Modern Event Entity (Matter, modern Zigbee/ZHA/Z2M remotes)
        if entity_id and entity_id.startswith("event."):
            event_type_map = {
                ACTION_PRESS: "press",
                ACTION_DOUBLE_PRESS: "double_press",
                ACTION_TRIPLE_PRESS: "multi_press_3",
                ACTION_LONG_PRESS: "long_press",
                ACTION_RELEASE: "release",
                ACTION_ROTATE_CW: "press",
                ACTION_ROTATE_CCW: "press",
            }
            target_event_type = event_type_map.get(action_type, "press")

            return [
                {
                    "platform": "state",
                    "entity_id": entity_id,
                    "attribute": "event_type",
                    "to": target_event_type,
                }
            ]

        # Case B: ZHA Event Bus trigger
        if protocol == "zha" and device_id:
            command_map = {
                ACTION_PRESS: "on",
                ACTION_DOUBLE_PRESS: "double",
                ACTION_LONG_PRESS: "hold",
                ACTION_RELEASE: "release",
            }
            return [
                {
                    "platform": "event",
                    "event_type": "zha_event",
                    "event_data": {
                        "device_id": device_id,
                        "command": command_map.get(action_type, "on"),
                    },
                }
            ]

        # Case C: Generic / Device Automation trigger
        if device_id:
            return [
                {
                    "platform": "device",
                    "device_id": device_id,
                    "domain": "device_automation",
                    "type": action_type,
                }
            ]

        # Fallback to state change on target entity
        return [
            {
                "platform": "state",
                "entity_id": entity_id or "event.switch_button_1",
            }
        ]

    def _build_conditions(self, condition_flows: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """Generate condition blocks."""
        built_conditions = []
        for c in condition_flows:
            ctype = c.get("type")
            if ctype == "sun_after_sunset":
                built_conditions.append({
                    "condition": "sun",
                    "after": "sunset",
                })
            elif ctype == "sun_before_sunrise":
                built_conditions.append({
                    "condition": "sun",
                    "before": "sunrise",
                })
            elif ctype == "time_range":
                built_conditions.append({
                    "condition": "time",
                    "after": c.get("after", "22:00:00"),
                    "before": c.get("before", "06:00:00"),
                })
            elif ctype == "state_check" and c.get("entity_id"):
                built_conditions.append({
                    "condition": "state",
                    "entity_id": c["entity_id"],
                    "state": c.get("state", "on"),
                })
        return built_conditions

    def _build_actions(self, action_cfg: dict[str, Any]) -> list[dict[str, Any]]:
        """Synthesize action sequence."""
        service = action_cfg.get("service", "light.toggle")
        target_entity = action_cfg.get("target_entity")
        preset = action_cfg.get("preset")

        # Preset 1: Smooth Dimmer Up (+10%)
        if preset == "dim_up" or service == "light.brightness_step_up":
            return [
                {
                    "service": "light.turn_on",
                    "target": {"entity_id": target_entity},
                    "data": {"brightness_step_pct": 10},
                }
            ]

        # Preset 2: Smooth Dimmer Down (-10%)
        if preset == "dim_down" or service == "light.brightness_step_down":
            return [
                {
                    "service": "light.turn_on",
                    "target": {"entity_id": target_entity},
                    "data": {"brightness_step_pct": -10},
                }
            ]

        # Preset 3: Nightlight mode (10% brightness warm white)
        if preset == "nightlight":
            return [
                {
                    "service": "light.turn_on",
                    "target": {"entity_id": target_entity},
                    "data": {
                        "brightness_pct": 10,
                        "color_temp_kelvin": 2200,
                    },
                }
            ]

        # Preset 4: Master Off (All Lights in Area)
        if preset == "master_off":
            target = {}
            if action_cfg.get("area_id"):
                target["area_id"] = action_cfg["area_id"]
            else:
                target["entity_id"] = "all"
            return [
                {
                    "service": "light.turn_off",
                    "target": target,
                }
            ]

        # Standard Service Call
        action_dict: dict[str, Any] = {
            "service": service,
        }
        if target_entity:
            action_dict["target"] = {"entity_id": target_entity}

        if action_cfg.get("data"):
            action_dict["data"] = action_cfg["data"]

        return [action_dict]

    def to_yaml(self, automation_dict: dict[str, Any]) -> str:
        """Render formatted, human-readable YAML representation."""
        class IndentedDumper(yaml.SafeDumper):
            def increase_indent(self, flow=False, indentless=False):
                return super().increase_indent(flow, False)

        return yaml.dump(
            [automation_dict],
            Dumper=IndentedDumper,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )

    async def async_save_automation(self, automation_dict: dict[str, Any]) -> bool:
        """Persist automation into Home Assistant storage and reload automation system."""
        try:
            # 1. Save into SwitchMatrix dedicated storage registry
            saved_automations = await self.store.async_load() or []
            auto_id = automation_dict.get("id")

            # Replace or append
            updated = False
            for idx, item in enumerate(saved_automations):
                if item.get("id") == auto_id:
                    saved_automations[idx] = automation_dict
                    updated = True
                    break
            if not updated:
                saved_automations.append(automation_dict)

            await self.store.async_save(saved_automations)

            # 2. Also append/sync to Home Assistant automations.yaml if accessible
            await self._async_sync_to_automations_yaml(automation_dict)

            # 3. Reload automations in HA
            await self.hass.services.async_call("automation", "reload", blocking=False)
            _LOGGER.info("SwitchMatrix: Successfully saved and reloaded automation: %s", auto_id)
            return True
        except Exception as err:
            _LOGGER.exception("Failed to save automation: %s", err)
            return False

    async def async_delete_automation(self, auto_id: str) -> bool:
        """Remove automation from SwitchMatrix storage."""
        saved_automations = await self.store.async_load() or []
        filtered = [a for a in saved_automations if a.get("id") != auto_id]
        await self.store.async_save(filtered)
        await self.hass.services.async_call("automation", "reload", blocking=False)
        return True

    async def async_get_saved_automations(self) -> list[dict[str, Any]]:
        """Retrieve all SwitchMatrix generated automations."""
        return await self.store.async_load() or []

    async def _async_sync_to_automations_yaml(self, automation_dict: dict[str, Any]) -> None:
        """Sync created automation to HA core automations.yaml if file exists."""
        config_dir = self.hass.config.path()
        automations_file = os.path.join(config_dir, "automations.yaml")

        def _sync_io():
            if not os.path.exists(automations_file):
                return

            existing_data = []
            try:
                with open(automations_file, "r", encoding="utf-8") as f:
                    content = yaml.safe_load(f)
                    if isinstance(content, list):
                        existing_data = content
            except Exception as e:
                _LOGGER.warning("Could not read automations.yaml: %s", e)

            auto_id = automation_dict.get("id")
            updated = False
            for i, item in enumerate(existing_data):
                if isinstance(item, dict) and item.get("id") == auto_id:
                    existing_data[i] = automation_dict
                    updated = True
                    break

            if not updated:
                existing_data.append(automation_dict)

            with open(automations_file, "w", encoding="utf-8") as f:
                yaml.safe_dump(existing_data, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

        await self.hass.async_add_executor_job(_sync_io)
